---
# Add the ACL file to be used in views to match clients
- name: Add the Named ACLs file /etc/bind/named.acls.conf
  sudo: yes
  when: confignamedacl 
  template: src=etc/bind/named.acls.conf dest=/etc/bind/named.acls.conf owner=root group=bind mode=0644 backup=yes
  tags: 
    - configNamedAcl

