---
# Install a proper named.conf, but backs up the original
# We will do so, because we will add VIEWS, and many of the configs should be done per view
- name: Configure /etc/bind/named.conf
  sudo: yes
  when: confignamedconf 
  template: src=etc/bind/named.conf dest=/etc/bind/named.conf owner=root group=bind mode=0644 backup=yes
  tags: 
    - configNamedConf

